### ISSUE TITLE
EmuTOS 1.0/1.0.1 Xboot program "Autostart"

### ISSUE THREAD

**Issue by n0kturnal** [emutos/emutos#28]
Checked latest version of EmuTOS 1.0/1.0.1 and noticed that XBoot III cannot auto launch programs. Program supposed to be launched right after programs in AUTO folder. On TOS 2.06 it works as expected. Checked it on 520ST+ with Cloudy/Lighting ST.

**Comment by czietz** [comment]
Can you please post a screenshot of XBOOT? I'm not familiar with what you mean by "auto launch".

**Comment by n0kturnal** [comment]
Yes autostart, I was about to send screenshot.

**Comment by czietz** [comment]
XBOOT does this by registering the program in `NEWDESK.INF` as autostart application. But EmuTOS/EmuDesk uses `EMUDESK.INF`, instead. I'm afraid this is not easily fixable. (One could presumably patch XBOOT.)

**Comment by n0kturnal** [comment]
Ouch... Yes, so patching XBoot is the only way. Preferably by adding emutos detection and outputting valid emudesk.inf. I'm not familiar how emutos.inf is compatible with newdesk.inf though.

**Comment by czietz** [comment]
The syntax of EMUDESK.INF is fairly similar to NEWDESK.INF. As a quick test/hack, I changed C:\NEWDESK.INF inside XBOOT.PRG to C:\EMUDESK.INF and the autostart program was actually started! However, as you point out, to do this properly one needs to add EmuTOS detection; otherwise a patched XBOOT version would not work under Atari TOS, anymore.

**Comment by czietz** [comment]
As discussed in 2021 this is an issue that needs to be patched in XBOOT, _not_ in EmuTOS.
