### ISSUE TITLE
emutos-512k-1.1.1 supports atari-tt mode, but emutos-1024k-1.1.1 doesn't

### ISSUE THREAD

**Issue by kotenok2000** [emutos/emutos#33]
Why doesn't emutos-1024k-1.1.1 support atari-tt mode?
When i plug etos1024k.img rom in hatari i get "This TOS version does not work in tt/Falcon mode.
==> Switching to STE mode now."

**Comment by anodynesoftware** [comment]
Since you got this message from Hatari, it would have made more sense to ask the Hatari people.  If you had done so, they would have told you that this is a problem with old versions of Hatari.

Solution: either switch to the latest development version of Hatari, or use an EmuTOS 512K image.  There's no real reason to use the 1024K image for most users.

For future reference, we prefer that people use the EmuTOS mailing list to report issues. If you had checked the mailing list archives, you would have found that this question was answered some time ago.

**Comment by czietz** [comment]
Also see the Readme that came included with the 1024k ROM:
https://github.com/emutos/emutos/blob/93c42f04028581372b83f9f26fd7be3b8204ff59/doc/readme-1024k.txt#L7-L12
