### ISSUE TITLE
EmuTOS 256KB crash on MiSTer FPGA

### ISSUE THREAD

**Issue by capitaineflam25** [emutos/emutos#35]
![IMG_20221106_183100](https://user-images.githubusercontent.com/985702/200188150-3b65fb97-2f19-4e7e-aa52-13ec774498e2.jpg)

The 192KB works like a charm 🥰
But the 256K crash, even when trying from PRG.
It works only if configured as "STEroids" (The overclocked version of STe)

**Comment by czietz** [comment]
Thank you for pointing this out. I'll start a discussion on the [_emutos-devel_ mailing list](https://sourceforge.net/p/emutos/mailman/) since I don't have a MiSTer to reproduce the issue.

**Comment by ragnar76** [comment]
Could you please disable STeroids and Viking mode and test again? It works here with latest Atari_ST Core and STeroids enabled but as soon as enable Viking mode, it crashes.

![grafik](https://user-images.githubusercontent.com/1709576/200195245-cd4007e9-0a9a-49c7-b049-4b2cf907c2c5.png)

**Comment by capitaineflam25** [comment]
Excellent ! You've found it. Viking mode was activated and without it EmuTOS 256K is booting perfectly.

Thanks a lot, and sorry for the false issue 😕

**Comment by czietz** [comment]
Thank you, @ragnar76.

We'll still see if we can make EmuTOS more robust, i.e., to run correctly when Viking mode is enabled.

**Comment by vinriviere** [comment]
Good that you quickly found the issue 🙂
BTW, that's Viking mode?

**Comment by ragnar76** [comment]
Viking Mode emulates a Viking Graphics Card which was made fo the Mega ST (Megabus).

**Comment by czietz** [comment]
> Viking Mode emulates a Viking Graphics Card which was made fo the Mega ST (Megabus).

Yes. I even had a brief discussion on the mailing list about adding support (mainly for the real card): https://sourceforge.net/p/emutos/mailman/emutos-devel/thread/4866fec9-f7cb-5c0d-f769-a9dcfff5ce53%40gmx.net/?page=1#msg37375449

However, it turned out, that the implementation in MiST (not necessarily MiSTer) is not fully compatible to the real Viking card; plus it is different whether one runs in STEroids mode or not. This is why I abandoned adding native Viking support to EmuTOS, again.

That being said, I want at least to make sure that EmuTOS boots when Viking mode is enabled - so that users can then load the driver.

**Comment by czietz** [comment]
Fixed with commit 37e9d5d9. Now EmuTOS (256k and PRG versions) should boot on the MiSTer, even when Viking emulation is active.

Thank you to everyone involved in finding the root cause.
