### ISSUE TITLE
embedding emutos roms in vAmiga

### ISSUE THREAD

**Issue by mithrendal** [emutos/emutos#45]
We're reaching out to ask if it's alright with you for us to include the emutos-amiga.rom as an integrated replacement ROM within vAmiga. Would that be okay for you?

![vamigaemutos](https://github.com/emutos/emutos/assets/17108995/666a5ffb-193d-4c4a-ac02-a82fbef8b6c3)

`vAmigaWeb`
On the web-assembly PWA version of vAmiga, directly runnable at https://vamigaweb.github.io , we also aim to offer users the option to install emutos-amiga.rom with just a button click, similar to how we currently provide AROS kickstart replacement ROMs

We would be delighted if this is fine for you! 😀

currently we implement the `.st` floppy image format compatibility so that we can drag .st files into it.

native built for macOS
https://dirkwhoffmann.github.io/vAmiga/

PWA enabled for ipad, android, windows and all the others
https://vamigaweb.github.io/doc

**Comment by dirkwhoffmann** [comment]
First of all, great to see TOS running on an Amiga. I was unaware of this project until a couple of days ago. 

While adding .st file support to vAmiga, I ran into a strange issue. In general, there was hardly anything to do (except to support the .st suffix), as vAmiga can already handle MSDOS formatted disks.

The issue I am experiencing is related to the selected drive emulation in vAmiga. Sometimes, it works, sometimes it doesn't. In summary:

- With the standard settings in vAmiga (accurate drive emulation, highest compatibility), I get a read error at some point (the directory loads fine though): 
 
<img width="872" alt="316400269-06be6d1e-a2a5-45fe-86e3-68ade36b5a22" src="https://github.com/emutos/emutos/assets/12561945/0924c1c2-34a5-4d7b-8a52-e6411e8601a0">

However, the example game works fine...
- ...if I select a drive with infinite speed (in that case, vAmiga flushes all requested bytes in one chunk. In general, this mode is less compatible, but works well with EmuTOS)
- ... or if I compile vAmiga with debug option `ALIGN_HEAD`. This option sets the drive head position to position 0 on every head step. 
- ... or if I use extra long tracks (resulting in more padding bytes at the end of a track).

<img width="872" alt="317250753-4386f3e6-02b2-41ce-b97f-6ba5b942878d" src="https://github.com/emutos/emutos/assets/12561945/d7217c72-83e2-4b43-871b-058e5cf019bc">

I've reported my findings in more detail in [this issue](https://github.com/dirkwhoffmann/vAmiga/issues/821).

I can think of two scenarios:
1. There is some bug somewhere hidden in vAmiga. 
2. EmuTOS depends on the actual track layout, i.e., the number of bytes two consecutive tracks are shifted against each other on the disk. The `ALIGN_HEAD` observation somewhat points in this direction.

@czietz: Do you think scenario 2 could be a possibility? Based on my current findings, it's hard to tell where to look next.

**Comment by czietz** [comment]
Pulling in @vinriviere , as he is the developer of the Amiga support in EmuTOS.

**Comment by vinriviere** [comment]
Many thanks @mithrendal for this detailed report. To support Atari floppies in EmuTOS for Amiga, I initially used and adapted AROS disk routines. That worked well, but it wasn't possible to use that in official binaries due to incompatible software licenses. So I completely rewrote the floppy implementation, using the AROS code as inspiration. Maybe I missed something.
I can just say that I tested that code using:
- WinUAE
- Real Amiga + real floppy drive
- Real Amiga + Gotek drive with HxC firmware

Almost all the time, everything works perfectly. Sometimes I see that dreaded "Data on the disk in drive A: may be damaged." alert, but that's only occasionally. So I consider that the implementation is almost correct (even if it could still contain bugs in corner cases). 

However, some people reported having similar trouble, as I understand, more frequently. So something might indeed be wrong, or at least triggered with some specific hardware/configurations. Thanks to your detailed report, I think we should easily find the cause of the problem, and fix it. Of course floppy code on Amiga is tricky, but as I rewrote everything in the simplest and readable way, fixes should be easy. At least when the actual cause is identified.

I don't promise you to look at that immediately, but definitely, I will care about that issue. EmuTOS for Amiga is limited but supposed to work well, so I will do.

**Comment by mithrendal** [comment]
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/63c111a9-319c-45ee-b124-29f44b519097">

EmuTOS is now integrated into https://vAmigaWeb.github.io

the `learn more ...` links to https://emutos.sourceforge.io

it accepts `.ST` files

vAmigaWeb is a PWA and can be `installed` so that it works also when offline 🤓

**Comment by czietz** [comment]
Looks very nice! Thank you.

**Comment by vinriviere** [comment]
That's excellent 😃 Well done.
