### ISSUE TITLE
Falcon030 EmuTOS in ROM doe not find IDE Disk

### ISSUE THREAD

**Issue by dirkhohmann** [emutos/emutos#51]
Hi,
I put EmuTOS in ROM of an original Falcon030. It was previously running TOS4.04. 
EmuTOS does not find the build-in 60MByte IDE Disk.
I tried several kind of reset - no success.
Also interesting: I saw the startup-screen only at the very first boot, then never again.

Any Idea what happens ?

...it's really nice, that somebody is really working on stuff for such an old computer :-)

Dirk

**Comment by dirkhohmann** [comment]
Sorry, no success. I could do a cold start, see the start screen and delay it for infinite time by holding the shift key. But no way to access my IDE-Disk. Maybe I should mention that I have two partitions on that disk.
The disk is the original 60MB shipped with that machine.
Right now, I hesitate to rip it apart only to flash the image with the modified boot time... I have up to date flash in there, but was too lazy to design a download software for that - I though I wouldn't need it very often.

**Comment by dirkhohmann** [comment]
OK - Now I modified the Flash-Image, Boot-Time 2 Seconds. The start takes significantly longer - NO CHANGE.
So I must say: EmuTOS does not work with Original Falcon IDE Disks :-(

**Comment by czietz** [comment]
Thank you for the quick reply. I have started a thread on the mailing list, which is used for technical/development discussion. Feel free to join in. https://sourceforge.net/p/emutos/mailman/emutos-devel/

**Comment by vinriviere** [comment]
> I could do a cold start, see the start screen and delay it for infinite time by holding the shift key.

Sorry, this can't work. Because all disk detections are already finished when the welcome screen is displayed. The only way to add proper delay is to patch the ROM image as @czietz wrote.

> Now I modified the Flash-Image, Boot-Time 2 Seconds. The start takes significantly longer (longer than Original Boot Time) - NO CHANGE.

Oh. So there is something wrong. But it should work. Please join the EmuTOS mailing list as asked, and we will debug that. This will help other Falcon users, anyway.

**Comment by dirkhohmann** [comment]
![FalconBoot](https://github.com/user-attachments/assets/740bbe23-8147-4d48-8808-694305a35204)
Im in the mailing List.
I attached my TOS4.04 Startup showing the Disk Type ST9080A.
Even the manual is still available.
https://www.seagate.com/support/disc/manuals/ata/9235pmb.pdf.

**Comment by dirkhohmann** [comment]
OK, got the GIT-Repo and I'm able to build on Linux.
Could you give me some hints to start ?

**Comment by czietz** [comment]
The official tool chain for building EmuTOS is m68k-atari-mint cross-tools, maintained by @vinriviere : http://vincent.riviere.free.fr/soft/m68k-atari-mint/. (Other gcc versions for m68k have been reported to work, too; but are not officially supported and sometimes generate worse output.)

Since building EmuTOS is a bit outside the scope of this particular issue, I encourage you to join in on the discussion on the mailing list. Feel free to ask any questions about building EmuTOS there. 😃

**Comment by czietz** [comment]
Did you see Roger's email on the mailing list? We think we might have figured out what makes your drive not work with EmuTOS. But need you to test the theory, since no developer has an original Falcon IDE drive, anymore. 

If interested, please join in on the mailing list.

**Comment by dirkhohmann** [comment]
... already send a mail.
I'm in the mailing list and waiting for a test release ;-)
PRG-Release: I hope that I can put it in the AUTO-Folder of my Hard Disk, start the system with TOS4.04 and then still access the HD after that.
Alternative is a ROM Image what I can flash. But that's less comfortable. I must put the chips in an external programmer, because I didn't create a flash tool for the F30. My flash extension supports two TOS images, that's why I can always switch back to TOS4.04
I found one last floppy disk in my drawer.... ;-)

**Comment by czietz** [comment]
I hope you got Roger's reply on the emutos-devel list on Thursday, and you two are I contact now.

**Comment by czietz** [comment]
Fixed with commit 0c80a7149a6e237a7b51ba4d2467cb347f1b6576.
