### ISSUE TITLE
Desktop extends off bottom of monitor on North American Amiga

### ISSUE THREAD

**Issue by uityyy** [emutos/emutos#53]
**Hardware:**
- Amiga 1000 (NTSC)
- Analogue RGB connector
- Amiga 1080 (the Amiga 1000's original monitor)

**Symptom:**
In all selectable screen resolutions there is a large white margin at the top of the screen, and the desktop extends off the bottom of the screen to the extent that the trash and printer icons or at least their labels are invisible.\

This stock Amiga monitor does not have a vertical-position adjustment knob, and vertical positioning is correct when running Amiga Workbench. However, in EmuTOS the vertical positioning is incorrect even if the screen resolution is set to 640x200, which is the same as what Amiga Workbench is using.

**Comment by vinriviere** [comment]
Indeed. Currently, EmuTOS for Amiga only supports PAL machines. To support NTSC, it requires changing a few timings. Nothing complicated I guess, but that situation needs to be properly detected and handled. I plan to work on that some day.

**Comment by czietz** [comment]
I have made some changes to EmuTOS to (hopefully) support NTSC machines. However, I don't have any Amiga hardware; nor do I know someone with an NTSC Amiga. I only was able to test on WinUAE. Therefore, I didn't dare pushing my changes into official EmuTOS, yet. They reside in my fork until someone reviews and/or tests them: https://github.com/emutos/emutos/compare/master...czietz:emutos:amiga_ntsc

@uityyy : If you are willing to test my changes, let me know which variant (floppy disk, ROM?) you prefer and I'll build it for you.

**Comment by uityyy** [comment]
I am able to test an ADF floppy image. I have been using the one that takes the place of the Kickstart floppy since I have an Amiga 1000, which is the model without a Kickstart ROM.

**Comment by czietz** [comment]
Thank you. I've built a test version with my proposed NTSC changes. It is attached to this post. As mentioned, I could only test it on WinUAE, so a test on a real NTSC Amiga is greatly appreciated.

[emutos-kickdisk-NTSC-TEST.zip](https://github.com/user-attachments/files/17849588/emutos-kickdisk-NTSC-TEST.zip)

**Comment by uityyy** [comment]
Absolutely brilliant! With this version the default 640x400 "ST" resolution fits perfectly on screen as does the 640x200 "Falcon" option. I think the 640x200 resolution, which is identical to what I use in AmigaOS is the ideal choice for this machine as the refresh rate is slow enough for interlacing to be *very* flickery, but it's nice that the other option exists.

With this change the "Amiga" resolution options based on PAL machine specs now extend off both the top and bottom of the screen, but one should probably not be using a PAL resolution on an NTSC machine anyway. The 640x480 and 640x240 options are closer to fitting than the rest and actually close enough that if this machine were exclusively dedicated to EmuTOS, I would try adjusting he VSize POT on the back of the monitor, and they might be perfect.

640x200 test evidence attached. :-)
![EmuTOSNTSCAmiga1080](https://github.com/user-attachments/assets/8905625c-7955-467f-b35d-2828c3705d3e)

**Comment by vinriviere** [comment]
Superb 🤩 Indeed, this had to be done.

For PAL resolutions, I remember that I had precisely extracted the video settings values from hardware registers when using AmigaOS Workbench (certainly with WinUAE debugger) to mimic them in EmuTOS. Then I checked on my real PAL A500+, on the monitor the picture position was exactly the same between AmigaOS and EmuTOS in 640x256. Then I centered the other modes accordingly.

For NTSC resolutions, well, I have no way to test, as PAL and NTSC Amiga machines are physically different. But your test already shows that it works perfectly. And I guess that WinUAE is perfectly accurate in this regard.

Then, regarding to the 640x256 mode: indeed, it is certainly designed for PAL-only machines. It is even the default for the Workbench desktop. But visually, on real PAL hardware, the picture size 640x256 image looks just like your picture above (640x200 NTSC). This is because PAL is more "smashed" than NTSC, there is more room on top and bottom.

BTW, what are the standard resolutions on NTSC Amiga? I should check with WinUAE. My initial goal was to put into EmuTOS both standard Amiga video modes (for almost full screen support) and Atari video modes (for compatibility). If, as I suspect, 640x256 is a nonsense with NTSC, then we should remove it from the resolution dialog box.

**Comment by czietz** [comment]
Thank you @uityyy for testing! I pushed the changes as commit 950c0b25d40c6ca66b748c0fa7d07992090bc3ac now.

> If, as I suspect, 640x256 is a nonsense with NTSC, then we should remove it from the resolution dialog box.

Probably there are people better qualified to comment than me. I assume the NNNx256 and NNNx512 resolutions won't fit on an NTSC monitor as this only has 240 / 480 visible lines in non-interlaced / interlaced mode, respectively. So, yes, a nice followup commit would be to remove these resolutions from the dialog box for NTSC.
