### ISSUE TITLE
More floppy formatting options

### ISSUE THREAD

**Issue by danboid** [emutos/emutos#54]
I would like the EmuTOS floppy formatting tool to gain the ability to format double sided disks as 800 Kb and ideally also 820 Kb floppies if possible, which would largely remove the need to use something like https://atari.8bitchip.info/flofor.html.

I happen to quite enjoy using floppy disks still y'see.

**Comment by czietz** [comment]
I would consider a 800k (80 tracks, 10 sectors) option, if someone contributes it. Note though, there is little space left in the floppy format dialog, so a solution for this dialog needs to be found:
![grab0002](https://github.com/user-attachments/assets/05c4926c-d2db-47a7-a970-3ac1aeb3c7a0)

I'm skeptical about 820k (82 tracks, 10 sectors) because this is not supported by every floppy drive. I don't want people to erroneously report bugs against EmuTOS's format dialog, just because their drive does not support this many tracks. In the end, EmuTOS's format dialog is _not_ meant to replace highly specialized formatting programs such as (http://www.clausbrod.de/cgi-bin/view.pl/Atari/Hyperformat)[Hyperformat] et al.

**Comment by danboid** [comment]
It looks like we could squeeze in a drop down menu to pick the size of the disk on the size of the disk selection buttons, maybe? As you say, its pretty packed already, at least in low res.

I understand your concern about not wanting to include 820 Kb. I'd be happy with getting to choose between 720 and 800 Kb.

**Comment by czietz** [comment]
I've started working on this. You can follow any potential discussion on the mailing list https://sourceforge.net/p/emutos/mailman/emutos-devel/, which is our main means of communication.

**Comment by danboid** [comment]
Thanks Christian!

I have subd to the ml.

My EEPROM programmer should arrive in the next few days but I'm away until the 2nd so won't get to try it until then at the earliest.

**Comment by czietz** [comment]
Implemented with commit bbe298fe9c861a6b8c3c31ddc94001fa16c1f083.
