### ISSUE TITLE
Incompatibilities of EmuTOS

### ISSUE THREAD

**Issue by MrPetari** [emutos/emutos#9]
To EmuTOS team:  I tested only 4 programs myself with EmuTOS 0.9.9 192K v.
3 of them had issues. Clearly, some compatibility issues. I even wrote message from Sourceforge to project leader, what was sent to him as e-mail, I guess. So far, no any response. (3 days.).
I will try here - since on AF is not possible to talk normally. And yes, this is my last attempt. I have better things in my life to do. Just want to finish things as much possible, and to try as much has sense.

So, issue 1 is that false detection of key release. Overlong mess at AF about it. It is clear that docs are not enough detailed - no word about what exactly should return in d0 after calling that Ikbdsys vector function.
Issue 2 : Video player: That txt at page with incompatible SW, what says about my code searching some pattern - clearly prejudice. You seen couple of such, so assumed that is. And yes, it is at that place - that is last attempt to do the job, if regular way fails.
And regular way fails with EmuTOS because it uses total unusual, non standard way how hard disk driver and it's loading at boot work. Complaining on lack of space in ROM, then adding there hard disk driver ?
OK, but then make it as option, leaving option to use autoboot driver on disk. Don't see that it is possible. I assumed that some disk utils will not work, so checked. Indeed CHKDSK3 (Atari SW) has problems with absolute sector access. And that is dangerous situation. Some data corruption can happen if someone tries to edit sector on drive, and it goes on wrong place.

Issue 3 - the best case: I made some simple, AES call based demo. 3KB only. OK, let's try with EmuTOS, after tried with all reg. TOS versions.
There were 2 problems:  bad color of ball for slide  and  not moving mouse cursor during slide.
First one: I thought that it is bad palette in low res, but it is rather bad Icon color implementation. See later more ...
Second is bad implementation of Appl_play AES call.
And here we are at sheer essence of problems: bad documentation. 
In my ProfiBuch stays that 1 record is 6 bytes for Appl_play, and my handwritten correction from some 10 years ago that it is 8 bytes. Error #1 -  found while testing that 3K proggie.
There is other error:  Icon color related - Error #2 ....  But I tested my SW, and I seen that color is bad, so I corrected until got desired color. With Appl_play was no problem, since I had good literature - mine handwriting :-)
So, EmuTOS team made OS, but did not test many things - like that Appl_play AES call, and many other, I guess. Blindly relying on docs is mistake too. And Atari ST docs are really full with mistakes.
That's what I have as bug report. I hope that we can talk as normal people about all problems.
 
   PP

**Comment by vinriviere** [comment]
Thanks for your bug reports (even if normally 1 bug = 1 GitHub ussue).
I have just answered [there](https://www.exxoshost.co.uk/forum/viewtopic.php?f=39&t=442), so here is just a summary.

Issue 1: key release.
We have a different interpretation about what the ROM ikbdsys is supposed to leave in d0 after the call. We very well understood each other position in the [Atari-Forum discussion](http://www.atari-forum.com/viewtopic.php?p=334088#p334088). EmuTOS team considers that d0 is just a clobbered register not containing any intentional data. So this will not be changed in EmuTOS.

Issue 2: You are mentioning STVidPlay, which is indeed listed in [incompatible.txt](https://github.com/emutos/emutos/blob/master/doc/incompatible.txt)
Searching some "code pattern" is clearly bad practice, EmuTOS will not be compatible with that.
But you mention that "regular way" is failing. I would be curious to know what regular way is, maybe EmuTOS lacks something.
EmuTOS internal hard disk driver can't be disabled at runtime, but one can recompile EmuTOS without it.

Issue 3: simple, AES call based demo
I guess this is [that one](https://www.exxoshost.co.uk/forum/viewtopic.php?f=39&t=437).
- bad color of ball for slide: could be an EmuTOS bug or not, must be investigated.
- bad implementation of Appl_play AES call: could be indeed a bad implementation inside EmuTOS, as there are not much programs using that. Or something else. Must be investigated.

**Comment by MrPetari** [comment]
And you still ignoring whole bad documentation problem.
I said that there is error in docs about record size used in Appl_play (same stays for Rec too).
Maybe to start with that 8 instead 6 , and testing with concrete SW.
Regular way of hard disk driver boot, loading, running ...
That is longer topic. I can write something about it, of course not here,
Yep, maybe just to make version without own hard disk driver. Then will be 40 instead 20 versions :-)

To say again: what is diff, between us is approach. You want clean SW in not clean OS, using crappy docs. That just works not for me. I want compatibility and speed in first place.

**Comment by mfro0** [comment]
As MrPetari said:

> I said that there is error in docs about record size used in Appl_play (same stays for Rec too).

Indeed, there seems to be a problem with `appl_write()`. It doesen't seem to be related to the 6/8 byte difference you mention, however. EmuTOS uses `appl_write()` event buffers consisting of two long words that later TOS versions use as well.

If you have some test code that isolates and shows the problem, it would probably be very helpful to provide it here (ideally as source). You can attach a file to a message with drag & drop.

**Comment by MrPetari** [comment]
This message is mostly for mfro0 (mfro at AF, I guess)  :
So, now you asking me for some test code. Sure, I can provide it - I can put together some 500 bytes long proggie, where will be 40 bytes for concrete function test, and other is AES initialisation + other nesessary, ASM source too. Both - for Record and for play.
I made recording by using slightly modified demo, in Debugger.
Just to add that I pointed on that 6-8 byte diff. because it could propagate thru several docs. 
I just checked - initial low res palette is same in EmuTOS as in TOS 1.04 (or any other), so icon color error is indeed because bad Icon display code in EmuTOS - and what a shock ! Docs are not good about icon color.
Then, you asking me too about regular way how hard disk drivers autoboot, how they work. I find it strange, because there is a lot about it in ProfiBuch from 1991 . Probably not enough, and yes, may be mistakes there.  I don't know about other literature what could contain it.
Things are that me, as many other SW authors needed just to discover self a lot of things. I had no clue about how TOS deals with BigFAT16 - until about 2005 . Then I performed lot of tests, traces until realized how TOS deals with partitions over 32 MB.
And reminder on something really not nice: ""hey-I-recently-found-this-to-work-by-chance-super-cool-and-docs-are-for-lamers trick"" .  So, dear mfro, how is that now you ask me to do some extra contribution after that ? I think simply that you own me apologize. Not here, but at AF, in that thread,
Then maybe I will feel better, and will spend some time to do that test SW + to write little longer txt. about how hard disk drivers work under regular TOS versions.  Especially because those last posts there written by Eero (really did not read what should there) .
Please look on this as hand offered in purpose to make peace, and better understanding. 
PP

**Comment by mfro0** [comment]
>  I think simply that you own me apologize.
Only a very brief answer to that since it doesn't belong here:  I clearly indicated what I wrote there as my personal opinion. You didn't mention anything that would change my mind regarding dirty programming tricks, so frankly: no, I don't think I owe you anything.

Regarding the bug you found (`appl_trecord()` and `appl_tplay()`: yes, I think what you found is crearly a bug in EmuTOS and this will be fixed. Thank you for the bug report.

Never mind about the test case/program. I've written one myself in the meantime.

**Comment by MrPetari** [comment]
Well, I did not expect any attitude change. You still insult - I don't use dirty tricks. I use efficient tricks.
You and others in Hatari/EmuTOS team have no clue how to write fast and efficient code - EmuTOS is slow. Hatari eats 100% of 4GHz CPU core power - that's are FACTS.  
Thank you for trying to spend my time for something you can do yourself :-)
Case closed.

**Comment by mfro0** [comment]
> You and others in Hatari/EmuTOS team have no clue how to write fast and efficient code - EmuTOS is slow. Hatari eats 100% of 4GHz CPU core power - that's are FACTS.

- no need to insult the whole EmuTOS team just because you don't like **my** personal opinion.
- no need to insult the whole EmuTOS team for Hatari behaviour (and - before you insult them - no need to blame Hatari people for Atari TOS full of busy waiting CPU intensive loops)
- absolutely no need to make a fool out of yourself with all that complaints and insults (that's your own business, however, but we would very much appreciate if you could do that elsewhere)

**Comment by vinriviere** [comment]
Reminder: Purpose of GitHub issues is to improve the project, which here is EmuTOS.

So far I see:
- Potential issue with appl_tplay(). Differences in different TOS versions must be clarified.
- Potential issue with icon drawing.

Progress will be faster if we stay on topic.

**Comment by MrPetari** [comment]
OK. We well be at topic when some stop calling people dirty coder, while asking to provide test code - isn't it ironic ? No need to be ironic with self :-)
Not potential issues  - proved ones. And funny thing - in both cases there are errors in docs. Will not repeat myself what are concrete errors in docs - Atari ProfiBuch .

In my opinion, best progress would be to change whole approach. As is, EmuTOS tries impossible thing: to do it in clean way, using available docs. about TOS functions, descriptions how some parts work etc.
I think that even with much better and more complete docs that is too optimistic approach. Some things need to be checked in real work, to be sure about all details - and that may be very time demanding.
With Atari ST docs, as we have them: done in rush, with many errors, missing necessary details it is practically impossible. And yes, we know the result: low SW compatibility - ah, we are now at topic again.
You want to do it better than DRI/Atari programmers in 1994-1992 ? Go on ! Do it more clean, to work faster. That's nice idea. That some 20%-50% of existing large SW base will have some issues ? You don't care. Allright. You use it for own satisfaction. Atari people will just say: I don't need it - program X works not, Y is too slow, Z has some bad colors ....   This is how I see all it. Why new OS for oldie, when it supports not old, proved SW ?

**Comment by MrPetari** [comment]
Something very interesting:  looked A Hitchiker's Guide to the BIOS Rev 1.1 1990 .
There is example of DMA bus boot code (same is in ProfiBuch 1987). 
Why it is interesting - because Hatari and EmuTOS people called my hard disk driver buggy. Yes, there was 'bug' in older versions - they actually worked well with only 1 attached ACSI device. With 2 not.
I said then that I followed what was in ProfiBuch. And ProfiBuch followed what was in Hitchhiker's Guide :-)   So, my 'bug' was because crappy Atari DOC, actually main DOC for Atari ST. And what it has with EmuTOS ? A lot - it means that following crappy docs leads to problems in SW.
I hope that above was useful for someone. Look at it as Xmas gift.
Marry XMAS :-)

**Comment by anodynesoftware** [comment]
There has been much heat and just a little light in this. The appl_tplay() bug is fixed to the best of my knowledge. I recently fixed a bug in bit_blt() which could be related to the icon drawing problem mentioned above (since there was no other information provided, I can't be certain it is related).
So I'm now closing this.

**Comment by MrPetari** [comment]
"There has been much heat and just a little light in this. The appl_tplay() bug is fixed to the best of my knowledge. I recently fixed a bug in bit_blt() which could be related to the icon drawing problem mentioned above (since there was no other information provided, I can't be certain it is related).
So I'm now closing this."
Well, "best of my knowledge" ? Does it means that it is tested with concrete SW ?
Anyway, I'm closing myself and talk about EmuTOS :-)

**Comment by mfro0** [comment]
https://help.github.com/en/articles/blocking-a-user-from-your-organization
